spring:
  application:
    name: RegistroTareas

  datasource:
    url: jdbc:mysql://localhost:3306/tareas?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: root
    password: 3141
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    org.example.registrotareas: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

server:
  port: 8089
  servlet:
    context-path: /api